auto r_esp;               
auto r_eip;
AddBpt(BeginEA());    
StartDebugger("","",""); 
GetDebuggerEvent(WFNE_SUSP,-1); 
StepOver();
GetDebuggerEvent(WFNE_SUSP,-1);
r_esp=GetRegValue("esp");
Message("%x\n",r_esp);
AddBptEx(r_esp,4,BPT_WRITE);   
Message("%x\n",MaxEA());
RunTo(MaxEA());
GetDebuggerEvent(WFNE_SUSP,-1);
Message("%x\n",eip);
RunTo(eip+7);             
GetDebuggerEvent(WFNE_SUSP,-1);
StepOver();
GetDebuggerEvent(WFNE_SUSP,-1);
Message("OEP is %x",eip);